language: objective-c
#before_install: ./install_dependencies.sh

# build via xcodetest
#script: ./build_and_run_unit_tests.sh DemoUnitTest DemoUnitTestTests

script: travis-ci/script.sh
notifications:
  email:
    recipients:
      - dang.than@mulodo.com
    on_success: change #[always|never|change] #default: change
    on_failure: always #[always|never|change] #default: always

#before_install: "git submodule init && git submodule update && sudo gem update --system && sudo gem install bundler && bundle install"
#script: "bundle exec rake test --trace"

#before_install:
#- git submodule update --init --recursive

#scode_sdk: iphonesimulator


